### ISSUE TITLE
I'm using zeekcfg based on debian10 but i don't have a good entrypoint.sh

### ISSUE THREAD

**Issue by xx-zhang** [activecm/zeekcfg#5]
# I have using ur zeekcfg based on debian10 but i don't have a good  entrypoint.sh
> i've using your docker-zeek but need [malcolm](https://github.com/idaholab/Malcolm) of some scripts , so i using malcolm's docker and install your zeekcfg, but i don't have a good `entrypoint.sh` , could you help me . 

- there is a mater with `crond` not fond in `debian10`, and i replaced it with `crontab` with the error of `not run param -b`. 
- trap sometimes not run , and then i start zeek with `zeekcfg`  and stop with `ps -ef | grep zeek | grep -v grep | awk '{print $2}' | xargs kill -9` to kill the pid of starting zeek.

**Comment by ethack** [comment]
Zeekcfg is meant to create a node.cfg file, either interactively or with command line parameters. You can download the zeekcfg binary and use it outside of docker beforehand and then mount the node.cfg file into the container. Or you can embed zeekcfg inside the container and execute it in the entrypoint script if node.cfg isn't found. 

Based on your description it sounds like you might be confusing zeekcfg with zeekctl. Zeekctl is what uses the node.cfg file that zeekcfg creates. Zeekctl starts the zeek processes, compresses logs, can optionally monitor and restart them with `zeekctl cron`.

If you aren't using zeekctl then you don't need zeekcfg, cron/crontab, or traps (at least not to trap for log rotation like docker-zeek does). I haven't used Malcom but it looks like they are using supervisord rather than zeekctl to run zeek. And it doesn't look like they use zeek at all for live packet capture so there's really no need for zeekctl anyway. 

I'd ask the Malcom project for help if you're using their Dockerfile as a base. If you decide to use https://github.com/activecm/docker-zeek for a base feel free to open a new issue on that repo for help with more specifics like the scripts you're trying to integrate, the end goal you have in mind, and the entrypoint script you've created so far.
